# Mongo-Sync Configurations

local:
  db: 'test'                  # Your local database name
  host:
    port: 27017              # Local MongoDB port
  access:
    username: ''             # Local MongoDB username (if required)
    password: ''             # Local MongoDB password (if required)

remote:
  db: 'test'                 # Remote database name
  host:
    url: ''    # Remote server URL or IP
    port: 27017             # Remote MongoDB port
  access:
    username: 'username'     # Remote MongoDB username
    password: 'password'     # Remote MongoDB password
